In [1]:
import numpy as np

In [2]:
arr = np.arange(1,21)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [4]:
arr_copy = arr.copy()

In [5]:
arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [6]:
arr_copy[1:10] = 0

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
arr_copy

array([ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [9]:
arr_copy[:10] = 100

In [10]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [12]:
arr_copy[0:6] = 700

In [13]:
arr_copy

array([700, 700, 700, 700, 700, 700, 100, 100, 100, 100,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [14]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
boolean = arr > 10

In [16]:
arr[boolean]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
boolean

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [18]:
arr[arr > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
arr[arr % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [21]:
arr[arr % 4 == 0]

array([ 4,  8, 12, 16, 20])

In [22]:
arr[arr % 5 == 0]

array([ 5, 10, 15, 20])

In [23]:
big_arr = np.arange(1,101).reshape(10,10)

In [24]:
big_arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [26]:
big_arr[9,4:9]

array([95, 96, 97, 98, 99])

In [27]:
big_arr[4:6,3:5]

array([[44, 45],
       [54, 55]])

In [28]:
big_arr[8,7]

88

In [29]:
big_arr[6,5]

66

In [30]:
big_arr[5,7]

58