In [1]:
import numpy as np

In [2]:
arr = np.arange(1,21)

In [3]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [6]:
arr * arr * arr

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000, 1331,
       1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859, 8000])

In [7]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [8]:
arr + 3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23])

In [9]:
arr * 4

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68,
       72, 76, 80])

In [10]:
arr -5

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15])

In [11]:
arr / 6

array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333,
       1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        , 2.16666667, 2.33333333, 2.5       ,
       2.66666667, 2.83333333, 3.        , 3.16666667, 3.33333333])

In [12]:
np.cbrt(arr)

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059, 1.91293118, 2.        , 2.08008382, 2.15443469,
       2.22398009, 2.28942849, 2.35133469, 2.41014226, 2.46621207,
       2.5198421 , 2.57128159, 2.62074139, 2.66840165, 2.71441762])

In [14]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [15]:
ar = np.arange(10)

In [16]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.log(ar)

C:\Users\akash mishra\AppData\Local\Temp\ipykernel_4500\3877308065.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(ar)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [19]:
ar 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
1/ar

C:\Users\akash mishra\AppData\Local\Temp\ipykernel_4500\1444338822.py:1: RuntimeWarning: divide by zero encountered in divide
  1/ar


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [22]:
ar * 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
ar/ar

C:\Users\akash mishra\AppData\Local\Temp\ipykernel_4500\2192729293.py:1: RuntimeWarning: invalid value encountered in divide
  ar/ar


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [24]:
np.cos(ar)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [25]:
np.tan(ar)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [26]:
np.min(arr)

1

In [27]:
np.max(arr)

20

In [28]:
np.min(ar)

0

In [29]:
np.max(ar)

9

In [30]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
        0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206])

In [31]:
np.tan(arr)

array([ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,  1.15782128e+00,
       -3.38051501e+00, -2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
       -4.52315659e-01,  6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
        4.63021133e-01,  7.24460662e+00, -8.55993401e-01,  3.00632242e-01,
        3.49391565e+00, -1.13731371e+00,  1.51589471e-01,  2.23716094e+00])

In [32]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [33]:
np.exp(ar)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [34]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227])