In [1]:
import numpy as np

In [2]:
num_list = [1,2,3,4]

In [3]:
np.array(num_list)

array([1, 2, 3, 4])

In [4]:
my_num_list = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

In [5]:
np.array(my_num_list)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [6]:
np.arange(0,21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [12]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [14]:
from numpy.random import rand

In [15]:
from numpy.random import randn

In [16]:
from numpy.random import randint

In [17]:
rand(5,5)

array([[0.36738132, 0.64661187, 0.32799223, 0.78272815, 0.44895299],
       [0.79684649, 0.02369136, 0.20823379, 0.26096549, 0.21721522],
       [0.88004867, 0.77747095, 0.27884319, 0.7660861 , 0.17733782],
       [0.32521337, 0.34140147, 0.76111074, 0.12277359, 0.33698025],
       [0.18405549, 0.74212838, 0.02385726, 0.90980511, 0.55448597]])

In [18]:
randn(5,5)

array([[ 0.36013311, -0.73416061, -0.95305019,  1.2227938 ,  1.28723879],
       [ 1.28221432,  0.07004652, -1.69777334,  0.35177635,  0.48501435],
       [-2.25060358,  0.36020741, -0.08549562, -1.16528287, -1.15903091],
       [-0.2019318 , -0.42118812,  0.26325736,  0.00345363,  2.10664323],
       [-0.90818957,  1.28503273, -0.57536395, -0.89353982, -1.45585913]])

In [19]:
randn()

0.05986873686216418

In [20]:
randint(1,100,10)

array([43, 12, 39, 87, 88,  5, 89, 72, 73, 34])

In [21]:
array1 = np.arange(50)

In [22]:
array2 = randint(1,100,10)

In [23]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [24]:
array2

array([ 7, 10, 83, 54, 16, 52, 97, 28, 51, 60])

In [31]:
arr = array1.reshape(5,10)

In [27]:
array2.max()

97

In [28]:
array2.min()

7

In [29]:
array2.argmax()

6

In [30]:
array2.argmin()

0

In [32]:
arr.shape

(5, 10)

In [33]:
arr.dtype

dtype('int32')